config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
    registrations: 'users/registrations' 
  }

  devise_scope :user do  
    get '/users/sign_out' => 'devise/sessions#destroy'
  end

  resources :jobs do
    collection do 
      get :scrape
    end
    member do 
      post :addJob
    end
  end

  resources :users do
    resources :jobs do
      collection do
          get :miniIndex
      end
    end
  end

  root "jobs#home"
end

app/models/job.rb
class Job < ApplicationRecord
    belongs_to :user, optional: true

    require 'geocoder'
    require 'selenium-webdriver'
    # webdriver needed for selenium to run on production server (without local copy of chrome)
    require 'webdrivers/chromedriver'

    $scrapedJobs = nil

    def self.convertAddress(address, location)
        result = Geocoder.search(address)
        # Set location originally searched for as deafult if geocode cant find location
        baseLocation = Geocoder.search(location)
        # Check a result has been found & it's in the uk
        if result.first.present? && result.first.country_code === "gb"
            return result.first.coordinates          
        else 
            return baseLocation.first.coordinates
        end
    end

    def self.underMaxSalary(salaryMax, jobSalary)
        result = false
        # Check if salary max is even required & return tru if not
        if salaryMax != "none"
            # Strip desired salary max entered by user of letters & convert to workable number
            cleanSalaryMax = salaryMax.tr('^0-9', '').to_i
            # Check if job included a salary range in the description with a hyphen
            if jobSalary.include? "-"
                # Strip job salary description of all but numbers and remove any prior to hyphen
                newJobSalary = jobSalary.gsub(/.*-/, '').tr('^0-9', '').to_i
                if newJobSalary <= cleanSalaryMax
                    result = true
                end
            else
                result = true
            end
        else
            result = true 
        end
        result
    end

    def self.jobList(url, location, salaryMax = "none")
        # container to hold jobs:
        jobs = Array.new
 
        # Specifying chrome path (only needed in production, comment out for local development)
        Selenium::WebDriver::Chrome.path = "/usr/bin/google-chrome"

        # configuring Chrome to run in headless mode 
        options = Selenium::WebDriver::Chrome::Options.new

        windows_useragent = "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/88.0.4324.104 Safari/537.36"
        # linux_useragent = "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/88.0.4324.96 Safari/537.36"
        options.add_argument("--disable-blink-features=AutomationControlled")
        options.add_argument("--no-sandbox")
        options.add_argument("user-agent=#{windows_useragent}")
        options.add_argument("--disable-web-security")
        options.add_argument("--disable-xss-auditor")
        options.add_option("excludeSwitches", ["enable-automation", "load-extension"])
        options.add_argument("--headless")
        # Add location of binary for production
        options.binary = "/usr/bin/google-chrome"
        
        # initializing the Selenium Web Driver for Chrome 
        driver = Selenium::WebDriver.for :chrome, options: options 

        # driver.execute_script("Object.defineProperty(navigator, 'webdriver', {get: () => undefined})")
        
        # visiting a web page in the browser opened by Selenium behind the scene 
        driver.get(url)

        # Manage time to load 
        driver.manage.timeouts.implicit_wait = 10
 
        job_listings = driver.find_element(xpath: '//div[@data-genesis-element="CARD_GROUP_CONTAINER"]')
        job_box = job_listings.find_elements(tag_name: 'article')
        job_box.each do |job_item|
           job = {
                  title: job_item.find_element(xpath: './/a[@data-at="job-item-title"]').text,
                  location: job_item.find_element(xpath: './/span[@data-at="job-item-location"]').text,
                  #Fix the salary below, just taking the first jobs one, same class as location
                  salary: job_item.find_element(xpath: './/span[@data-at="job-item-salary-info"]').text,
                  link: job_item.find_element(xpath: './/a[@data-at="job-item-title"]').attribute('href'),
                  latlong: convertAddress(job_item.find_element(xpath: './/span[@data-at="job-item-location"]').text, location)
            }
            # Check if job salary is above max salary input, dont add to jobs array if it is
            if underMaxSalary(salaryMax, job[:salary]) == true 
                jobs << job
            end
        end
        # Close the driver
        driver.quit

        jobs # Return the array here
    end
    
    def self.scrape(job, location, radius)
        # Get job & location in format ready for url (no spaces between words)
        cleanJob = job.gsub(" ", "-")
        cleanLocation = location.gsub(" ", "-")
        url = 'https://www.totaljobs.com/jobs/'+cleanJob+'/in-'+cleanLocation+'?radius='+radius
        result = jobList(url, location)
        $scrapedJobs = result
        return result
    end

    def self.getURL(cleanJob, location, radius, remote, salaryMin)
        url = 'https://www.totaljobs.com/jobs/'
        # Deal with remote option
        if remote == "1"
            url << 'work-from-home/'
        end
        url << cleanJob+'/in-'+location+'?'
        # Deal with minimum salary option
        if salaryMin != "none"
            cleanSalaryMin = salaryMin.tr('^0-9', '')
            url << 'salary='+cleanSalaryMin+'&salarytypeid=1&radius='+radius+'&action=facet_selected%3bsalary%3b'+cleanSalaryMin+'%3bsalarytypeid%3b1'
        else
            url << 'radius='+radius
        end    
        # Return completed url
        url
    end

    def self.advancedScrape(job, location, radius, remote = 0, salaryMin, salaryMax)
        # Get job & location in format ready for url (no spaces between words)
        cleanJob = job.gsub(" ", "-")
        cleanLocation = location.gsub(" ", "-")
        url = getURL(cleanJob, cleanLocation, radius, remote, salaryMin)
        result = jobList(url, location, salaryMax)
        $scrapedJobs = result
        return result
    end
end

app/controllers/jobs_controller.rb
class JobsController < ApplicationController
  #before_action :set_job, only: %i[ show edit update destroy ]
  # Disable CRF
  protect_from_forgery with: :null_session
  skip_before_action :verify_authenticity_token

  skip_before_action :authenticate_user!, only: [:scrape], :raise => false

  def scrape 
    job = params[:job]
    location = params[:location]
    radius = params[:radius]
    advanced = params[:advanced]
    # Handle simple & advanced search differently
    if advanced == "1"
      remote = params[:remote]
      salaryMin = params[:salaryMin]
      salaryMax = params[:salaryMax]
      #secondJob = params[:secondJob]
      @scrape = Job.advancedScrape(job, location, radius, remote, salaryMin, salaryMax)
    else 
      @scrape = Job.scrape(job, location, radius)
    end
    # Dont generate map or go to another page if no job results were scraped
    if @scrape.length == 0 
      redirect_to root_path, alert: "No Jobs found, please try another search." 
    end
    # create gon variable of the jobs that can be accessed by js 
    gon.scrape = @scrape
  end

  # GET /jobs or /jobs.json
  def index
    @jobs = current_user.jobs

    # Convert saved jobs into same format as scrape for map display purposes
    result = []
    list = @jobs.as_json
    list.each do |job|
      coords = [job["latitude"].to_f, job["longitude"].to_f]
      job.merge!({"latlong" => coords})
      result << job.except("id", "latitude", "longitude", "created_at", "updated_at")
    end
    # Set gon variable to result
    gon.scrape = result
  end

  # Small index in modal
  def miniIndex
    @jobs = current_user.jobs
  end

  # Add job to saved list (triggered by js)
  def addJob
    # From the post request url get the index number of the job
    index = request.path.tr('^0-9', '').to_i
    # Get the job from the scraped jobs global variable
    job = $scrapedJobs[index]

    title = job[:title]
    location = job[:location]
    salary = job[:salary]
    link = job[:link]
    latlong = job[:latlong]
    latitude = latlong[0]
    longitude = latlong[1]

    create(title, location, salary, link, latitude, longitude)
  end

  # POST /jobs or /jobs.json
  def create (title, location, salary, link, latitude, longitude)
    @job = Job.new(title: title, location: location, salary: salary, link: link, latitude: latitude, longitude: longitude)
   
    @job.user_id = current_user.id
    
    respond_to do |format|
      if @job.save
        format.html { redirect_to job_url(@job), notice: "Job was successfully created." }
        format.json { render :show, status: :created, location: @job }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @job.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /jobs/1 or /jobs/1.json
  def destroy
    @job = Job.find(params[:id])
    @job.destroy

    respond_to do |format|
      format.html { redirect_to jobs_url, notice: "Job was successfully removed." }
      format.json { head :no_content }
    end
  end

  def show
    @job = Job.find(params[:id])
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    #def set_job
    #  @job = Job.find(params[:id])
    #end

    # Only allow a list of trusted parameters through.
    #def job_params
    #  params.fetch(:job, {})
    #  params.require(:job).permit(:title, :location, :salary, :link)
    #end
end

app/helpers/jobs_helper.rb
module JobsHelper
end

app/views/jobs/_form.html.erb
<%= form_with(model: job) do |form| %>
  <% if job.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(job.errors.count, "error") %> prohibited this job from being saved:</h2>

      <ul>
        <% job.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/jobs/_job.html.erb
<div id="<%= dom_id job %>" class="job-item">
    <div class="job-desc">
        <h4><%= job.title %></h4>
        <p><%= job.location %></p>
        <p><%= job.salary %></p>
        <p><%= job.link %></p>
    </div>
    <%#= button_to "Delete", job, method: :delete, data: {turbo: "false"} %>
    <%= button_to(image_tag('bin.png', id: "bin"), job, method: :delete, data: {turbo: "false"}, id: "delete" ) %>
</div>

app/views/jobs/edit.html.erb
<h1>Editing job</h1>

<%= render "form", job: @job %>

<br>

<div>
  <%= link_to "Show this job", @job %> |
  <%= link_to "Back to jobs", jobs_path %>
</div>

app/views/jobs/home.html.erb
<div class="home">
    <h2>Search for jobs and display the results on a map</h2>
    <p><i>Pic of example search (with exact job details changed to examples and styling complete)</i></p>
    <p>Please note - Job searches (especially common jobs in a large radius) may take 3-10 seconds.</p>
    <div class="about">
        <p>
            Create an account (it's free and only requires an email & password) to save jobs for later 
            or build up your own map of all the jobs you're interested in.
        </p>
    </div>
    <div class="disclaimer">
        <p><i>
            Disclaimer:
            All jobs are scraped from Totaljobs and link back to their website to view the full job description.
            There's no intention to steal traffic here, merely provide an alternative view of the data...
            and add a few new fetaures along the way.
        </i></p>
    </div>
</div>

app/views/jobs/index.html.erb
<%= include_gon %>

<div class="index">
  <h2><%=@jobs.length%> Jobs Saved</h2>

  <% provide :head_tags do %>
    <%= javascript_import_module_tag "map" %>
  <% end %>
  <div id="map" data: {@scrape.to_json}></div>

  <div id="jobs">
    <% @jobs.each do |job| %>
      <%= render job %>
    <% end %>
  </div>
</div>

app/views/jobs/miniIndex.html.erb
<%= turbo_frame_tag "modal" do %>
  <div class="modal">
      <div id="jobs">
          <% @jobs.each do |job| %>
              <%= render job %>
          <% end %>
      </div>
      <%= link_to "Go to map view", user_jobs_path, class: "map-view-link", data: {turbo: "false"} %>
      <%= link_to "Cancel", "#", data: {
        controller: "modals",
        action: "modals#close"
      }, class: "cancel-link" %>
  </div>
<% end %>

app/views/jobs/new.html.erb
<h1>New job</h1>

<%= render "form", job: @job %>

<br>

<div>
  <%= link_to "Back to jobs", jobs_path %>
</div>

app/views/jobs/scrape.html.erb
<%= include_gon %>

<div class="scraped">
  <h2><%=@scrape.length%> Jobs found</h2>

  <% provide :head_tags do %>
    <%= javascript_import_module_tag "map" %>
  <% end %>
  <div id="map" data: {@scrape.to_json}></div>

</div>

app/views/jobs/show.html.erb
<%= render @job %>

<div>
  <%= link_to "Edit this job", edit_job_path(@job) %> |
  <%= link_to "Back to jobs", jobs_path %>

  <%= button_to "Destroy this job", @job, method: :delete %>
</div>