config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
    registrations: 'users/registrations' 
  }

  devise_scope :user do  
    get '/users/sign_out' => 'devise/sessions#destroy'
  end

  resources :jobs do
    collection do 
      get :scrape
    end
    member do 
      post :addJob
    end
  end

  resources :users do
    resources :jobs do
      collection do
          get :miniIndex
      end
    end
  end

  root "jobs#home"
end

app/views/shared/_footer.html.erb
<div id="footer">
    <div class="personal">
        <p>This site was built using Ruby on rails & vanilla JS, check out the full source code here:</p>
        <a href="https://github.com/James-rae-eng/job-map" target="_blank" >
            <img src="https://cdn.jsdelivr.net/gh/devicons/devicon/icons/github/github-original.svg" class="icon"/>
        </a>
    </div>
    <div class="personal">
        <p>See more of my other projects or get in touch:</p>
        <a href="https://www.google.com" target="_blank">www.google.com</a>
    </div>
    <div class="personal">
        <p><i>Compass icon created by Azland Studio - Flaticon</i></p>
    </div>    
</div>

app/views/shared/_search.html.erb
<%= form_tag scrape_jobs_path, method: :get, data: {turbo: "false"} do %>
  <div class="search_form">
    <div class="search_fields">
      <div id="simple_search">
        <div>
          <label for="job">Job</label>
          <%= text_field_tag :job %>
        </div>
        <div>
          <label for="location">Location</label>
          <%= text_field_tag :location %>
        </div>
        <div>
          <label for="radius">Radius</label>
          <%= select_tag :radius, options_for_select([5, 10, 20, 30]) %>
        </div>
        <div>
          <label for="advanced">Advanced search</label>
          <%= check_box_tag :advanced %>
        </div>
      </div>

      <div id="extra_search" style="display:none;">
        <div>
          <label for="remote">Work from home only</label>
          <%= check_box_tag :remote %>
        </div>
        <div>
          <label for="salaryMin">Salary min</label>
          <%= select_tag :salaryMin, options_for_select(["none", "£10,000", "£20,000", "£30,000", "£40,000", "£50,000", "£60,000", "£70,000", "£80,000", "£90,000", "£100,000"]) %>
        </div>
        <div>
          <label for="salaryMax">Salary max (optional)</label>
          <%= select_tag :salaryMax, options_for_select(["none", "£20,000", "£30,000", "£40,000", "£50,000", "£60,000", "£70,000", "£80,000", "£90,000", "£110,000"]) %>
        </div>

        <%#label for="secondJob">Additional job title (warning this increases search time)</label>
        <%#= text_field_tag :secondJob %>
      </div>
    </div>
    <%= submit_tag "Search", id: "search_button"%>
  </div>
<% end %>

app/views/shared/_topbar.html.erb
<div class="topbar">
    <a href=<%=root_path%> id="home">
        <p>J</p>
        <%= image_tag"compass.png", id: "compass"%>
        <p>B-Map</p>
    </a>

    <% if user_signed_in? %>
        <div class="sign-links">
            <%= link_to "Saved jobs", miniIndex_user_jobs_path(current_user), data: { turbo_frame: "modal" } %>
            <%= link_to 'Sign out', destroy_user_session_path, method: :delete %>
        </div>
    <% else %>
        <div class="sign-links">
            <%= link_to 'Sign in', new_user_session_path %>
            <%= link_to 'Sign up', new_user_registration_path %>
        </div>
    <% end %>
</div>